apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherman
  template:
    metadata:
      labels:
        app: weatherman
    spec:
      containers:
        - name: weatherman
          image: weatherman:latest
          imagePullPolicy: IfNotPresent
