apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-server
  template:
    metadata:
      labels:
        app: log-server
    spec:
      containers:
      - name: log-server
        image: log-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: log-server
spec:
  selector:
    app: log-server
  ports:
    - port: 80
      targetPort: 80
