apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaker
  template:
    metadata:
      labels:
        app: leaker
    spec:
      containers:
        - name: leaker
          image: leaker:latest
          imagePullPolicy: IfNotPresent
